### ISSUE TITLE
Problem Gallery

### ISSUE THREAD

**Issue by przemasisko** [gjr-osweb/zpbase#3]
Hello,
gallery displays incorrectly on Goole Chrome web browser 41.0.XXX.XX. 36.0.1 Firefox and Internet Explorer 11 is functioning correctly.
Does not work Gallery Index Layout and image size.
Version zp-Base: 1.1, ZenPhoto: 1.4.7.
Regards.

**Comment by gjr-osweb** [comment]
Cannot reproduce, working fine for me.
